# Site settings
title: India Bergeland
name: India Bergeland

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/ibergeland/
 - title: GitHub
   url: https://github.com/ibergeland93

#Any buzzword skills you want to include
skills:
 - Python
 - Numpy
 - Pandas
 - SQL
 - AMPL
 - Next Generation Sequencing
 - DNA/RNA

#Work experience is required
roles:
 - title: Senior Engineer
   start: 2016
   end: Ongoing
   employer: Emerald Street Ventures
   description: Emerald Street Ventures was established as an incubator vehicle for the development of a number of software and legal-tech projects, and a rapidly growing, London-based start-up using innovative technologies to revolutionise and change the software and legal-tech landscape. Working with a range of cutting edge technologies and techniques including Scala, Cassandra, CoreOS, a variety of Machine Learning techniques.
 - title: Senior Engineer
   start: 2012
   end: 2016
   employer: Covestor
   description: Covestor is an investment marketplace startup that was successfully acquired by Interactive Brokers in 2015. <br/> I am a senior engineer working closely with the CTO, working across the full-stack, I am involved in all aspects of the technology including the website and back-end services.
 - title: Associate Manager
   start: 2005
   end: 2012
   employer: Accenture
   description: A range of functional and technical roles, primarily working on client sites in Financial Services.

#Education is required
education:
 - level: Master of Engingeering (M. Eng)
   date: Spring 2019
   subject: Industrial Engineering / Operations Research, Data Science
   focus: Genetic Data Science
   school: University of California, Berkeley
 - level: Bachelor of Science (B.S.)
   date: Fall 2015
   subject: Industrial Engineering / Operations Research
   school: Purdue University

#List of interesting Github repo/projects to include - optional
github:
 - ibergeland93/capstone


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>JVM</strong>: My background in Industrial Engineering and Operations Research as both an Undergraduate and Graduate student has developed me into a critical thinker and optimization seeker. Experience in Python and SQL, coupled with a background in probability theory and optimization analytics, allows me to approach projects with decisiveness. <br/><br/>
   <strong>Data Science</strong>: I work mostly in Python, but have fundamental understanding of R. The packages in Python I am comfortable working with are Numpy, Pandas, Matplotlib, and Scikit. I have worked with large genetic data sets – normalizing them before using feature engineering methods such as PCA and KEGG Pathways before modeling with SVM, Logistic Regression, and Mediboost.<br/><br/>
   <strong>Microbiology</strong>: Solid understanding of next generation sequencing for RNA and DNA, specifically in library preparation of RNA’s, through experience in customer and product development for stealth start-up. Experience working with Omics data in candidates predisposed to developing diabetes. Familiar with KEGG Pathways, BioPython, and HUGO.<br/><br/>
   
