# Site settings
title: India Bergeland
name: India Bergeland

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/ibergeland/
 - title: GitHub
   url: https://github.com/ibergeland93

#Any buzzword skills you want to include
skills:
 - Python
 - Numpy
 - Pandas
 - SQL
 - AMPL
 - Next Generation Sequencing
 - DNA/RNA

#Work experience is required
projects:
 - title: Steps Omics Approach to Weight Loss
   start: Aug 2018
   end: May 2019
   project type: Industry partner
   industry partner: UCSF Computational Genomics Lab 
   description: From clinical trial participants, consolidate omics data and behavioral data using Python. Feature engineering using PCA and KEGG Pathways. Model approach with Log Regression, SVM, and Mediboost.
 - title: *placeholder for UCSF Volunteer projects*
   start: Jan 2019
   end: July 2019
   project type: Volunteer
   Organization: UCSF Computational Genomics Lab
   description: *placeholder*
 - title: *placeholder for DataX project*
   start: Jan 2019
   end: May 2019
   project type: Academic
   description: *placeholder*

#Education is required
education:
 - level: Master of Engingeering (M. Eng)
   date: Spring 2019
   subject: Industrial Engineering / Operations Research, Data Science
   focus: Genetic Data Science
   school: University of California, Berkeley
 - level: Bachelor of Science (B.S.)
   date: Fall 2015
   subject: Industrial Engineering / Operations Research
   school: Purdue University

#List of interesting Github repo/projects to include - optional
github:
 - ibergeland93/capstone


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo:
   My background in Industrial Engineering and Operations Research as both an Undergraduate and Graduate student has developed me into a critical thinker and optimization seeker. Experience in Python and SQL, coupled with a background in probability theory and optimization analytics, allows me to approach projects with decisiveness. <br/><br/>
   <strong>Data Science</strong>: I work mostly in Python, but have fundamental understanding of R. The packages in Python I am comfortable working with are Numpy, Pandas, Matplotlib, and Scikit. I have worked with large genetic data sets – normalizing them before using feature engineering methods such as PCA and KEGG Pathways before modeling with SVM, Logistic Regression, and Mediboost.<br/><br/>
   <strong>Microbiology</strong>: Solid understanding of next generation sequencing for RNA and DNA, specifically in library preparation of RNA’s, through experience in customer and product development for stealth start-up. Experience working with Omics data in candidates predisposed to developing diabetes. Familiar with KEGG Pathways, BioPython, and HUGO.<br/><br/>
   
